// AUTOGENERATED FILE - DO NOT EDIT

var pt = window.PropTypes;
var pk = window['dash_echartsx'];

pk.DashEChartsX.propTypes = {id:pt.oneOfType([pt.string]),
 className:pt.oneOfType([pt.string]),
 style:pt.any,
 option:pt.any,
 notMerge:pt.oneOfType([pt.bool]),
 lazyUpdate:pt.oneOfType([pt.bool]),
 renderer:pt.oneOf(['canvas','svg']),
 theme:pt.oneOfType([pt.object,pt.oneOf(["light"]),pt.oneOf(["dark"])]),
 click_data:pt.any,
 dblclick_data:pt.any,
 hover_data:pt.any,
 selected_data:pt.any,
 legend_status:pt.any,
 zoom_data:pt.any,
 dispatch_action:pt.any,
 ref:pt.oneOfType([pt.string,pt.any]),
 key:pt.oneOfType([pt.string,pt.number])};
